import type {LedgerRepository,Ledger,Movement,Obligation,DailyExpense} from '../domain/finance';
import {dateForDay} from '../domain/finance';
import {reference} from '../domain/seed';
import type {DatabaseClient} from './database';

export class D1LedgerRepository implements LedgerRepository{
 constructor(private readonly db:DatabaseClient,private readonly userId='legacy',private readonly seedReference=true){}
 async read(month:string):Promise<Ledger>{const [o,m,e]=await this.db.batch([
  this.db.prepare('SELECT id,month,name,category,amount,note,cutoff_date AS cutoffDate,due_date AS dueDate,series_id AS seriesId,cutoff_day AS cutoffDay,due_day AS dueDay,total_debt AS totalDebt,bank,banking_url AS bankingUrl,interest_mv AS interestMV,interest_ea AS interestEA FROM obligations WHERE user_id=? AND month=? ORDER BY rowid').bind(this.userId,month),
  this.db.prepare('SELECT id,month,kind,obligation_id AS obligationId,amount,date,description FROM movements WHERE user_id=? AND month=? ORDER BY date DESC,rowid DESC').bind(this.userId,month),
  this.db.prepare('SELECT id,month,category,amount,date,description FROM daily_expenses WHERE user_id=? AND month=? ORDER BY date DESC,rowid DESC').bind(this.userId,month)
 ]);return {obligations:(o.results as unknown as Obligation[]).map(item=>({...item,cutoffDate:item.cutoffDay!=null?dateForDay(month,item.cutoffDay):item.cutoffDate,dueDate:item.dueDay!=null?dateForDay(month,item.dueDay):item.dueDate})),movements:m.results as unknown as Movement[],expenses:e.results as unknown as DailyExpense[]}}
 async initialize(month:string){
  if(this.seedReference){const existing=await this.db.prepare('SELECT id FROM obligations WHERE user_id=? AND month=? LIMIT 1').bind(this.userId,'2026-08').first();if(!existing){const statements=reference.flatMap(([name,amount,category,paid,date],i)=>{const id=this.userId==='legacy'?`2026-08-${i}`:`${this.userId}:2026-08-${i}`,movementId=this.userId==='legacy'?`import-${i}`:`${this.userId}:import-${i}`;const rows=[this.db.prepare('INSERT OR IGNORE INTO obligations (user_id,id,month,name,category,amount,note,series_id,recurring_amount) VALUES (?,?,?,?,?,?,?,?,?)').bind(this.userId,id,'2026-08',name,category,amount,'Importado de tu imagen',id,amount)];if(paid)rows.push(this.db.prepare('INSERT OR IGNORE INTO movements (user_id,id,month,kind,obligation_id,amount,date,description) VALUES (?,?,?,?,?,?,?,?)').bind(this.userId,movementId,'2026-08','payment',id,amount,date,'Pago registrado en la imagen'));return rows});await this.db.batch(statements)}}
  const exists=await this.db.prepare('SELECT id FROM obligations WHERE user_id=? AND month=? LIMIT 1').bind(this.userId,month).first();if(exists)return;
  const prior=await this.db.prepare('SELECT month FROM obligations WHERE user_id=? AND month<? ORDER BY month DESC LIMIT 1').bind(this.userId,month).first<{month:string}>();if(!prior)return;
  await this.db.prepare("INSERT OR IGNORE INTO obligations (user_id,id,month,name,category,amount,note,series_id,cutoff_day,due_day,total_debt,bank,banking_url,interest_mv,interest_ea,recurring_amount) SELECT ?,? || ':' || ? || ':' || COALESCE(series_id,id),?,name,category,recurring_amount,'',COALESCE(series_id,id),COALESCE(cutoff_day,CAST(strftime('%d',cutoff_date) AS INTEGER)),COALESCE(due_day,CAST(strftime('%d',due_date) AS INTEGER)),total_debt,bank,banking_url,interest_mv,interest_ea,recurring_amount FROM obligations WHERE user_id=? AND month=?").bind(this.userId,this.userId,month,month,this.userId,prior.month).run();
 }
 async addMovement(m:Movement){let result;if(m.kind==='payment'){result=await this.db.prepare(`INSERT OR IGNORE INTO movements (user_id,id,month,kind,obligation_id,amount,date,description) SELECT ?,?,?,'payment',?,?,?,? FROM obligations o WHERE o.user_id=? AND o.id=? AND o.month=? AND o.amount IS NOT NULL AND ?<=o.amount-COALESCE((SELECT SUM(amount) FROM movements WHERE user_id=? AND obligation_id=o.id AND kind='payment'),0)`).bind(this.userId,m.id,m.month,m.obligationId,m.amount,m.date,m.description,this.userId,m.obligationId,m.month,m.amount,this.userId).run()}else result=await this.db.prepare('INSERT OR IGNORE INTO movements (user_id,id,month,kind,obligation_id,amount,date,description) VALUES (?,?,?,?,?,?,?,?)').bind(this.userId,m.id,m.month,m.kind,null,m.amount,m.date,m.description).run();if(!result.meta.changes&&!(await this.db.prepare('SELECT id FROM movements WHERE user_id=? AND id=? AND month=?').bind(this.userId,m.id,m.month).first()))throw new Error('El abono supera el saldo pendiente o la obligación no tiene valor definido.')}
 async saveObligation(o:Obligation,applyFutureAmount=false){
  const existing=await this.db.prepare('SELECT series_id AS seriesId,recurring_amount AS recurringAmount FROM obligations WHERE user_id=? AND id=? AND month=?').bind(this.userId,o.id,o.month).first<{seriesId:string|null;recurringAmount:number|null}>();const seriesId=existing?.seriesId??o.id;const recurringAmount=applyFutureAmount||!existing||!['Créditos','Tarjetas'].includes(o.category)?o.amount:existing.recurringAmount;
  const cutoff=o.cutoffDay===undefined?o.cutoffDate:dateForDay(o.month,o.cutoffDay),due=o.dueDay===undefined?o.dueDate:dateForDay(o.month,o.dueDay);const values=[o.cutoffDay??null,o.dueDay??null,o.totalDebt??null,o.bank??'',o.bankingUrl??'',o.interestMV??null,o.interestEA??null];
  const currentPaid=await this.db.prepare("SELECT COALESCE(SUM(amount),0) AS total FROM movements WHERE user_id=? AND obligation_id=? AND kind='payment'").bind(this.userId,o.id).first<{total:number}>();if((o.amount??0)<Number(currentPaid?.total??0))throw new Error('El valor no puede ser menor que los pagos registrados en el mes seleccionado.');
  if(applyFutureAmount){const invalid=await this.db.prepare("SELECT future.id FROM obligations future WHERE future.user_id=? AND future.series_id=? AND future.month>? AND COALESCE(?,0)<COALESCE((SELECT SUM(amount) FROM movements WHERE user_id=? AND obligation_id=future.id AND kind='payment'),0) LIMIT 1").bind(this.userId,seriesId,o.month,o.amount,this.userId).first();if(invalid)throw new Error('El valor no puede ser menor que los pagos registrados en los meses siguientes incluidos.')}
  const paidGuard="COALESCE(?,0)>=COALESCE((SELECT SUM(amount) FROM movements WHERE user_id=? AND obligation_id=? AND kind='payment'),0)";
  const results=await this.db.batch([
   this.db.prepare(`INSERT INTO obligations (user_id,id,month,name,category,amount,note,cutoff_date,due_date,series_id,cutoff_day,due_day,total_debt,bank,banking_url,interest_mv,interest_ea,recurring_amount) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE ${paidGuard} ON CONFLICT(id) DO UPDATE SET name=excluded.name,category=excluded.category,amount=excluded.amount,note=excluded.note,cutoff_date=excluded.cutoff_date,due_date=excluded.due_date,series_id=excluded.series_id,cutoff_day=excluded.cutoff_day,due_day=excluded.due_day,total_debt=excluded.total_debt,bank=excluded.bank,banking_url=excluded.banking_url,interest_mv=excluded.interest_mv,interest_ea=excluded.interest_ea,recurring_amount=excluded.recurring_amount WHERE obligations.user_id=excluded.user_id AND obligations.month=excluded.month`).bind(this.userId,o.id,o.month,o.name,o.category,o.amount,o.note,cutoff,due,seriesId,...values,recurringAmount,o.amount,this.userId,o.id),
   this.db.prepare(`UPDATE obligations SET cutoff_day=?,due_day=?,total_debt=?,bank=?,banking_url=?,interest_mv=?,interest_ea=?,cutoff_date=NULL,due_date=NULL WHERE user_id=? AND series_id=? AND month>? AND EXISTS(SELECT 1 FROM obligations WHERE user_id=? AND id=? AND month=?)`).bind(...values,this.userId,seriesId,o.month,this.userId,o.id,o.month),
   this.db.prepare(`UPDATE obligations SET amount=?,recurring_amount=? WHERE user_id=? AND series_id=? AND month>? AND ?=1 AND NOT EXISTS(SELECT 1 FROM movements WHERE user_id=? AND obligation_id=obligations.id AND kind='payment' GROUP BY obligation_id HAVING SUM(amount)>COALESCE(?,0))`).bind(o.amount,o.amount,this.userId,seriesId,o.month,Number(applyFutureAmount),this.userId,o.amount)
  ]);if(!results[0].meta.changes)throw new Error('El valor no puede ser menor que los pagos registrados en el mes seleccionado.')
 }
 async removeMovement(id:string,month:string){await this.db.prepare('DELETE FROM movements WHERE user_id=? AND id=? AND month=?').bind(this.userId,id,month).run()}
 async saveExpense(e:DailyExpense){await this.db.prepare(`INSERT INTO daily_expenses (user_id,id,month,category,amount,date,description) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category=excluded.category,amount=excluded.amount,date=excluded.date,description=excluded.description WHERE daily_expenses.user_id=excluded.user_id AND daily_expenses.month=excluded.month`).bind(this.userId,e.id,e.month,e.category,e.amount,e.date,e.description).run()}
 async removeExpense(id:string,month:string){await this.db.prepare('DELETE FROM daily_expenses WHERE user_id=? AND id=? AND month=?').bind(this.userId,id,month).run()}
}
