import type {LedgerRepository,Ledger,Movement,Obligation,DailyExpense,BalanceTransfer,ObligationCarry,ObligationHistoryEvent} from '../domain/finance';
import {dateForDay,LedgerError,followingMonth} from '../domain/finance';
import {reference} from '../domain/seed';
import type {DatabaseClient} from './database';

export class D1LedgerRepository implements LedgerRepository{
 constructor(private readonly db:DatabaseClient,private readonly userId='legacy',private readonly seedReference=true){}
 async read(month:string):Promise<Ledger>{const [o,m,e,t,c,h]=await this.db.batch([
  this.db.prepare('SELECT id,month,name,category,CASE WHEN amount IS NULL THEN NULL ELSE amount+COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=obligations.user_id AND target_id=obligations.id),0) END AS amount,note,cutoff_date AS cutoffDate,due_date AS dueDate,series_id AS seriesId,cutoff_day AS cutoffDay,due_day AS dueDay,total_debt AS totalDebt,bank,banking_url AS bankingUrl,interest_mv AS interestMV,interest_ea AS interestEA ,COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=obligations.user_id AND source_id=obligations.id),0) AS transferredAmount,COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=obligations.user_id AND target_id=obligations.id),0) AS receivedAmount FROM obligations WHERE user_id=? AND month=? ORDER BY rowid').bind(this.userId,month),
  this.db.prepare('SELECT id,month,kind,obligation_id AS obligationId,amount,date,description FROM movements WHERE user_id=? AND month=? ORDER BY date DESC,rowid DESC').bind(this.userId,month),
  this.db.prepare('SELECT id,month,category,amount,date,description FROM daily_expenses WHERE user_id=? AND month=? ORDER BY date DESC,rowid DESC').bind(this.userId,month),
  this.db.prepare("SELECT id,from_month AS fromMonth,to_month AS toMonth,amount,created_at AS createdAt,CASE WHEN to_month=? THEN 'incoming' ELSE 'outgoing' END AS direction FROM balance_transfers WHERE user_id=? AND (from_month=? OR to_month=?) ORDER BY created_at DESC,id").bind(month,this.userId,month,month),
  this.db.prepare('SELECT * FROM obligation_carries WHERE user_id=? AND (from_month=? OR to_month=?) ORDER BY created_at,id').bind(this.userId,month,month),
  this.db.prepare('SELECT * FROM obligation_history WHERE user_id=? AND month=? ORDER BY recorded_at DESC,id DESC').bind(this.userId,month)
 ]);return {obligations:(o.results as unknown as Obligation[]).map(item=>({...item,cutoffDate:item.cutoffDay!=null?dateForDay(month,item.cutoffDay):item.cutoffDate,dueDate:item.dueDay!=null?dateForDay(month,item.dueDay):item.dueDate})),movements:m.results as unknown as Movement[],expenses:e.results as unknown as DailyExpense[],transfers:t.results as unknown as BalanceTransfer[],carries:c.results as unknown as ObligationCarry[],history:h.results as unknown as ObligationHistoryEvent[]}}
 async carryObligation(id:string,month:string,obligationId:string,reason:string){
  await this.db.transaction(async tx=>{
   if(await tx.prepare('SELECT id FROM obligation_carries WHERE id=? AND user_id=? AND from_month=?').bind(id,this.userId,month).first())return;
   const next=followingMonth(month),repo=new D1LedgerRepository(tx,this.userId,false),ledger=await repo.read(month),source=ledger.obligations.find(o=>o.id===obligationId);
   if(!source||source.amount===null)throw new LedgerError('Define el valor de la obligación antes de trasladarla.');
   const amount=source.amount-ledger.movements.filter(m=>m.kind==='payment'&&m.obligationId===source.id).reduce((s,m)=>s+m.amount,0)-(source.transferredAmount??0);
   if(amount<=0)throw new LedgerError('La obligación no tiene saldo pendiente para trasladar.');
   const raw=await tx.prepare('SELECT * FROM obligations WHERE user_id=? AND id=? AND month=?').bind(this.userId,source.id,month).first<Record<string,string|number|null>>();
   const series=raw!.series_id??source.id;
   const matches=(await tx.prepare('SELECT id,amount FROM obligations WHERE user_id=? AND month=? AND COALESCE(series_id,id)=?').bind(this.userId,next,series).all<{id:string;amount:number|null}>()).results;
   if(matches.length>1)throw new LedgerError('Hay varias obligaciones de la misma serie en el mes siguiente. Revisa los duplicados.');
   let target=matches[0];
   if(!target){if(raw!.recurring_amount===null)throw new LedgerError('Define la cuota recurrente o la obligación del siguiente mes antes de trasladar.');const targetId=this.userId+':'+next+':'+series;
    await tx.prepare("INSERT INTO obligations(user_id,id,month,name,category,amount,note,series_id,cutoff_day,due_day,total_debt,bank,banking_url,interest_mv,interest_ea,recurring_amount) SELECT ?,?,?,name,category,recurring_amount,'',COALESCE(series_id,id),COALESCE(cutoff_day,CAST(strftime('%d',cutoff_date) AS INTEGER)),COALESCE(due_day,CAST(strftime('%d',due_date) AS INTEGER)),total_debt,bank,banking_url,interest_mv,interest_ea,recurring_amount FROM obligations WHERE user_id=? AND id=?").bind(this.userId,targetId,next,this.userId,source.id).run();target={id:targetId,amount:Number(raw!.recurring_amount)};
   }
   const alreadyReceived=Number((await tx.prepare('SELECT COALESCE(SUM(amount),0) AS total FROM obligation_carries WHERE user_id=? AND target_id=?').bind(this.userId,target.id).first<{total:number}>())?.total??0);
   if(target.amount===null||target.amount+alreadyReceived+amount>999999999999)throw new LedgerError('Define un valor válido en la obligación del siguiente mes antes de trasladar.');
   await tx.batch([tx.prepare('INSERT INTO obligation_carries(id,user_id,source_id,target_id,from_month,to_month,amount,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,this.userId,source.id,target.id,month,next,amount,reason,Date.now())]);
  });
 }
 async updatePaymentDate(id:string,month:string,date:string){
  const result=await this.db.prepare("UPDATE movements SET date=? WHERE user_id=? AND id=? AND month=? AND kind='payment'").bind(date,this.userId,id,month).run();
  if(!result.meta.changes) throw new LedgerError('El pago ya no está disponible. Actualiza los movimientos.');
 }
 async transferBalance(id:string,month:string,toMonth:string,amount:number){
  // One atomic insert represents both sides and rechecks available funds under the write lock.
  const result=await this.db.prepare(`INSERT OR IGNORE INTO balance_transfers (id,user_id,from_month,to_month,amount,created_at)
   SELECT ?,?,?,?,?,? WHERE ? <=
   COALESCE((SELECT SUM(CASE WHEN kind='income' THEN amount ELSE -amount END) FROM movements WHERE user_id=? AND month=?),0)
   - COALESCE((SELECT SUM(amount) FROM daily_expenses WHERE user_id=? AND month=?),0)
   + COALESCE((SELECT SUM(CASE WHEN to_month=? THEN amount ELSE -amount END) FROM balance_transfers WHERE user_id=? AND (from_month=? OR to_month=?)),0)
  `).bind(id,this.userId,month,toMonth,amount,Date.now(),amount,this.userId,month,this.userId,month,month,this.userId,month,month).run();
  if(!result.meta.changes){
   const existing=await this.db.prepare('SELECT amount,to_month AS toMonth FROM balance_transfers WHERE id=? AND user_id=? AND from_month=?').bind(id,this.userId,month).first<{amount:number;toMonth:string}>();
   if(existing?.amount===amount && existing.toMonth===toMonth)return;
   throw new LedgerError('No se pudo trasladar: el saldo disponible cambió o el importe supera el disponible. Actualiza el mes e intenta nuevamente.');
  }
 }
 async initialize(month:string){
  if(this.seedReference){const existing=await this.db.prepare('SELECT id FROM obligations WHERE user_id=? AND month=? LIMIT 1').bind(this.userId,'2026-08').first();if(!existing){const statements=reference.flatMap(([name,amount,category,paid,date],i)=>{const id=this.userId==='legacy'?`2026-08-${i}`:`${this.userId}:2026-08-${i}`,movementId=this.userId==='legacy'?`import-${i}`:`${this.userId}:import-${i}`;const rows=[this.db.prepare('INSERT OR IGNORE INTO obligations (user_id,id,month,name,category,amount,note,series_id,recurring_amount) VALUES (?,?,?,?,?,?,?,?,?)').bind(this.userId,id,'2026-08',name,category,amount,'Importado de tu imagen',id,amount)];if(paid)rows.push(this.db.prepare('INSERT OR IGNORE INTO movements (user_id,id,month,kind,obligation_id,amount,date,description) VALUES (?,?,?,?,?,?,?,?)').bind(this.userId,movementId,'2026-08','payment',id,amount,date,'Pago registrado en la imagen'));return rows});await this.db.batch(statements)}}
  const exists=await this.db.prepare('SELECT id FROM obligations WHERE user_id=? AND month=? LIMIT 1').bind(this.userId,month).first();if(exists)return;
  const prior=await this.db.prepare('SELECT month FROM obligations WHERE user_id=? AND month<? ORDER BY month DESC LIMIT 1').bind(this.userId,month).first<{month:string}>();if(!prior)return;
  await this.db.prepare("INSERT OR IGNORE INTO obligations (user_id,id,month,name,category,amount,note,series_id,cutoff_day,due_day,total_debt,bank,banking_url,interest_mv,interest_ea,recurring_amount) SELECT ?,? || ':' || ? || ':' || COALESCE(series_id,id),?,name,category,recurring_amount,'',COALESCE(series_id,id),COALESCE(cutoff_day,CAST(strftime('%d',cutoff_date) AS INTEGER)),COALESCE(due_day,CAST(strftime('%d',due_date) AS INTEGER)),total_debt,bank,banking_url,interest_mv,interest_ea,recurring_amount FROM obligations WHERE user_id=? AND month=?").bind(this.userId,this.userId,month,month,this.userId,prior.month).run();
 }
 async addMovement(m:Movement){let result;if(m.kind==='payment'){result=await this.db.prepare(`INSERT OR IGNORE INTO movements (user_id,id,month,kind,obligation_id,amount,date,description) SELECT ?,?,?,'payment',?,?,?,? FROM obligations o WHERE o.user_id=? AND o.id=? AND o.month=? AND o.amount IS NOT NULL AND ?<=o.amount+COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=o.user_id AND target_id=o.id),0)-COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=o.user_id AND source_id=o.id),0)-COALESCE((SELECT SUM(amount) FROM movements WHERE user_id=? AND obligation_id=o.id AND kind='payment'),0)`).bind(this.userId,m.id,m.month,m.obligationId,m.amount,m.date,m.description,this.userId,m.obligationId,m.month,m.amount,this.userId).run()}else result=await this.db.prepare('INSERT OR IGNORE INTO movements (user_id,id,month,kind,obligation_id,amount,date,description) VALUES (?,?,?,?,?,?,?,?)').bind(this.userId,m.id,m.month,m.kind,null,m.amount,m.date,m.description).run();if(!result.meta.changes&&!(await this.db.prepare('SELECT id FROM movements WHERE user_id=? AND id=? AND month=?').bind(this.userId,m.id,m.month).first()))throw new Error('El abono supera el saldo pendiente o la obligación no tiene valor definido.')}
 async saveObligation(o:Obligation,applyFutureAmount=false){
  const incoming=Number((await this.db.prepare('SELECT COALESCE(SUM(amount),0) AS total FROM obligation_carries WHERE user_id=? AND target_id=?').bind(this.userId,o.id).first<{total:number}>())?.total??0);
  if(o.amount!==null&&o.amount<incoming)throw new LedgerError('El valor no puede ser menor que el saldo trasladado recibido.');
  o={...o,amount:o.amount===null?null:o.amount-incoming};
  const existing=await this.db.prepare('SELECT series_id AS seriesId,recurring_amount AS recurringAmount FROM obligations WHERE user_id=? AND id=? AND month=?').bind(this.userId,o.id,o.month).first<{seriesId:string|null;recurringAmount:number|null}>();const seriesId=existing?.seriesId??o.id;const recurringAmount=applyFutureAmount||!existing||!['Créditos','Tarjetas'].includes(o.category)?o.amount:existing.recurringAmount;
  const cutoff=o.cutoffDay===undefined?o.cutoffDate:dateForDay(o.month,o.cutoffDay),due=o.dueDay===undefined?o.dueDate:dateForDay(o.month,o.dueDay);const values=[o.cutoffDay??null,o.dueDay??null,o.totalDebt??null,o.bank??'',o.bankingUrl??'',o.interestMV??null,o.interestEA??null];
  const carried=await this.db.prepare('SELECT COALESCE(SUM(amount),0) AS total FROM obligation_carries WHERE user_id=? AND source_id=?').bind(this.userId,o.id).first<{total:number}>();
  const currentPaid=await this.db.prepare("SELECT COALESCE(SUM(amount),0) AS total FROM movements WHERE user_id=? AND obligation_id=? AND kind='payment'").bind(this.userId,o.id).first<{total:number}>();if((o.amount??0)+incoming<Number(currentPaid?.total??0)+Number(carried?.total??0))throw new Error('El valor no puede ser menor que los pagos registrados en el mes seleccionado.');
  if(applyFutureAmount){const invalid=await this.db.prepare("SELECT future.id FROM obligations future WHERE future.user_id=? AND future.series_id=? AND future.month>? AND COALESCE(?,0)+COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=future.user_id AND target_id=future.id),0)-COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=future.user_id AND source_id=future.id),0)<COALESCE((SELECT SUM(amount) FROM movements WHERE user_id=? AND obligation_id=future.id AND kind='payment'),0) LIMIT 1").bind(this.userId,seriesId,o.month,o.amount,this.userId).first();if(invalid)throw new Error('El valor no puede ser menor que los pagos registrados en los meses siguientes incluidos.')}
  const paidGuard="COALESCE(?,0)>=COALESCE((SELECT SUM(amount) FROM movements WHERE user_id=? AND obligation_id=? AND kind='payment'),0)";
  const results=await this.db.batch([
   this.db.prepare(`INSERT INTO obligations (user_id,id,month,name,category,amount,note,cutoff_date,due_date,series_id,cutoff_day,due_day,total_debt,bank,banking_url,interest_mv,interest_ea,recurring_amount) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE ${paidGuard} ON CONFLICT(id) DO UPDATE SET name=excluded.name,category=excluded.category,amount=excluded.amount,note=excluded.note,cutoff_date=excluded.cutoff_date,due_date=excluded.due_date,series_id=excluded.series_id,cutoff_day=excluded.cutoff_day,due_day=excluded.due_day,total_debt=excluded.total_debt,bank=excluded.bank,banking_url=excluded.banking_url,interest_mv=excluded.interest_mv,interest_ea=excluded.interest_ea,recurring_amount=excluded.recurring_amount WHERE obligations.user_id=excluded.user_id AND obligations.month=excluded.month`).bind(this.userId,o.id,o.month,o.name,o.category,o.amount,o.note,cutoff,due,seriesId,...values,recurringAmount,o.amount===null?null:o.amount+incoming-Number(carried?.total??0),this.userId,o.id),
   this.db.prepare(`UPDATE obligations SET cutoff_day=?,due_day=?,total_debt=?,bank=?,banking_url=?,interest_mv=?,interest_ea=?,cutoff_date=NULL,due_date=NULL WHERE user_id=? AND series_id=? AND month>? AND EXISTS(SELECT 1 FROM obligations WHERE user_id=? AND id=? AND month=?)`).bind(...values,this.userId,seriesId,o.month,this.userId,o.id,o.month),
   this.db.prepare(`UPDATE obligations SET amount=?,recurring_amount=? WHERE user_id=? AND series_id=? AND month>? AND ?=1 AND NOT EXISTS(SELECT 1 FROM movements WHERE user_id=? AND obligation_id=obligations.id AND kind='payment' GROUP BY obligation_id HAVING SUM(amount)>COALESCE(?,0)+COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=obligations.user_id AND target_id=obligations.id),0)-COALESCE((SELECT SUM(amount) FROM obligation_carries WHERE user_id=obligations.user_id AND source_id=obligations.id),0))`).bind(o.amount,o.amount,this.userId,seriesId,o.month,Number(applyFutureAmount),this.userId,o.amount)
  ]);if(!results[0].meta.changes)throw new Error('El valor no puede ser menor que los pagos registrados en el mes seleccionado.')
 }
 async removeMovement(id:string,month:string){await this.db.prepare('DELETE FROM movements WHERE user_id=? AND id=? AND month=?').bind(this.userId,id,month).run()}
 async saveExpense(e:DailyExpense){await this.db.prepare(`INSERT INTO daily_expenses (user_id,id,month,category,amount,date,description) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category=excluded.category,amount=excluded.amount,date=excluded.date,description=excluded.description WHERE daily_expenses.user_id=excluded.user_id AND daily_expenses.month=excluded.month`).bind(this.userId,e.id,e.month,e.category,e.amount,e.date,e.description).run()}
 async saveExpenses(expenses:DailyExpense[]){await this.db.batch(expenses.map(e=>this.db.prepare(`INSERT INTO daily_expenses (user_id,id,month,category,amount,date,description) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category=excluded.category,amount=excluded.amount,date=excluded.date,description=excluded.description WHERE daily_expenses.user_id=excluded.user_id AND daily_expenses.month=excluded.month`).bind(this.userId,e.id,e.month,e.category,e.amount,e.date,e.description)))}
 async removeExpense(id:string,month:string){await this.db.prepare('DELETE FROM daily_expenses WHERE user_id=? AND id=? AND month=?').bind(this.userId,id,month).run()}
}
