export type FirebaseConfig={apiKey:string;projectId:string;serviceAccountEmail?:string;serviceAccountPrivateKey?:string};
export type FirebaseProfile={uid:string;email:string;emailVerified:boolean;displayName:string};
export class FirebaseError extends Error{constructor(message:string,readonly code:string,readonly status=400){super(message)}}

const jsonHeaders={'Content-Type':'application/json'};
const base64Url=(value:Uint8Array|string)=>{const bytes=typeof value==='string'?new TextEncoder().encode(value):value;let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')};
const firebaseMessage=(code:string)=>{
 const values:Record<string,string>={EMAIL_EXISTS:'Ya existe una cuenta con este correo.',EMAIL_NOT_FOUND:'Correo o contraseña incorrectos.',INVALID_PASSWORD:'Correo o contraseña incorrectos.',INVALID_LOGIN_CREDENTIALS:'Correo o contraseña incorrectos.',USER_DISABLED:'Esta cuenta no está habilitada.',INVALID_OOB_CODE:'El enlace no es válido o ya fue utilizado.',EXPIRED_OOB_CODE:'El enlace ya venció.',WEAK_PASSWORD:'La contraseña no cumple los requisitos de seguridad.',TOO_MANY_ATTEMPTS_TRY_LATER:'Demasiados intentos. Espera unos minutos antes de continuar.',OPERATION_NOT_ALLOWED:'Habilita Correo electrónico/Contraseña en Firebase Authentication.',CONFIGURATION_NOT_FOUND:'Firebase Authentication todavía no está configurado para este proyecto.',API_KEY_INVALID:'La clave web de Firebase no es válida.'};return values[code]??'Firebase Authentication no pudo completar la solicitud.';
};

export class FirebaseAuthService{
 private accessToken:{value:string;expiresAt:number}|null=null;
 constructor(private readonly config:FirebaseConfig,private readonly send:typeof fetch=fetch,private readonly now:()=>number=()=>Date.now()){}
 get adminConfigured(){const email=this.config.serviceAccountEmail?.trim()??'',key=this.config.serviceAccountPrivateKey?.replace(/\\n/g,'\n')??'';return /^[^@]+@[^@]+\.iam\.gserviceaccount\.com$/.test(email)&&key.includes('-----BEGIN PRIVATE KEY-----')&&key.includes('-----END PRIVATE KEY-----')&&key.length>500}
 private async response<T>(response:Response):Promise<T>{const value=await response.json().catch(()=>({})) as {error?:{message?:string}|string;error_description?:string}&T;if(!response.ok){const raw=typeof value.error==='string'?value.error_description??value.error:value.error?.message;const code=String(raw??'FIREBASE_ERROR').split(' : ')[0];throw new FirebaseError(firebaseMessage(code),code,response.status===429?429:400)}return value}
 private publicPost<T>(method:string,body:unknown){return this.send(`https://identitytoolkit.googleapis.com/v1/accounts:${method}?key=${encodeURIComponent(this.config.apiKey)}`,{method:'POST',headers:jsonHeaders,body:JSON.stringify(body)}).then(response=>this.response<T>(response))}
 async register(email:string,password:string,displayName:string){
  const created=await this.publicPost<{localId:string;idToken:string}>('signUp',{email,password,displayName,returnSecureToken:true});
  await this.publicPost('sendOobCode',{requestType:'VERIFY_EMAIL',idToken:created.idToken});return {uid:created.localId};
 }
 async login(email:string,password:string){const signed=await this.publicPost<{idToken:string}>('signInWithPassword',{email,password,returnSecureToken:true});const lookup=await this.publicPost<{users?:Array<{localId:string;email:string;emailVerified?:boolean;displayName?:string}>}>('lookup',{idToken:signed.idToken});const user=lookup.users?.[0];if(!user)throw new FirebaseError('No se pudo consultar la cuenta de Firebase.','USER_NOT_FOUND',404);return {uid:user.localId,email:user.email,emailVerified:!!user.emailVerified,displayName:user.displayName??''} satisfies FirebaseProfile}
 async requestPasswordReset(email:string){try{await this.publicPost('sendOobCode',{requestType:'PASSWORD_RESET',email})}catch(error){if(error instanceof FirebaseError&&error.code==='EMAIL_NOT_FOUND')return;throw error}}
 async confirmPasswordReset(oobCode:string,newPassword:string){await this.publicPost('resetPassword',{oobCode,newPassword})}
 private async oauthToken(){
  if(!this.adminConfigured)throw new FirebaseError('Falta importar la cuenta de servicio de Firebase para realizar esta acción administrativa.','FIREBASE_ADMIN_NOT_CONFIGURED',503);
  if(this.accessToken&&this.accessToken.expiresAt>this.now()+60000)return this.accessToken.value;const serviceAccountEmail=this.config.serviceAccountEmail!;const serviceAccountPrivateKey=this.config.serviceAccountPrivateKey!;const now=Math.floor(this.now()/1000),header=base64Url(JSON.stringify({alg:'RS256',typ:'JWT'})),payload=base64Url(JSON.stringify({iss:serviceAccountEmail,scope:'https://www.googleapis.com/auth/cloud-platform',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));
  const pem=serviceAccountPrivateKey.replace(/\\n/g,'\n').replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,'');const binary=atob(pem),der=Uint8Array.from(binary,character=>character.charCodeAt(0));const key=await crypto.subtle.importKey('pkcs8',der,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const signature=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(`${header}.${payload}`)));const assertion=`${header}.${payload}.${base64Url(signature)}`;
  const response=await this.send('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});const result=await this.response<{access_token:string;expires_in:number}>(response);this.accessToken={value:result.access_token,expiresAt:this.now()+result.expires_in*1000};return result.access_token;
 }
 private async adminPost<T>(path:string,body:unknown){const access=await this.oauthToken();const response=await this.send(`https://identitytoolkit.googleapis.com/v1/projects/${encodeURIComponent(this.config.projectId)}/${path}`,{method:'POST',headers:{...jsonHeaders,Authorization:`Bearer ${access}`},body:JSON.stringify(body)});return this.response<T>(response)}
 async createManagedUser(input:{email:string;password:string;displayName:string;emailVerified:boolean}){const result=await this.adminPost<{localId:string}>('accounts',{email:input.email,password:input.password,displayName:input.displayName,emailVerified:input.emailVerified,disableUser:false});return result.localId}
 async updateUser(uid:string,input:{emailVerified?:boolean;disabled?:boolean}){await this.adminPost('accounts:update',{localId:uid,...(input.emailVerified===undefined?{}:{emailVerified:input.emailVerified}),...(input.disabled===undefined?{}:{disableUser:input.disabled})})}
 async generatePasswordResetLink(email:string){const result=await this.adminPost<{oobLink:string}>('accounts:sendOobCode',{requestType:'PASSWORD_RESET',email,returnOobLink:true});return result.oobLink}
}
