import { createHash } from 'node:crypto';
import { z } from 'zod';
import ExcelJS from 'exceljs';
import { goalFields } from '../domain/goals';
import { BackupError, MAX_BACKUP_BYTES } from '../domain/month-backup';
import type { DatabaseClient } from './database';
const fields=z.object({id:z.string().uuid(),user_id:z.string().min(1).max(300),...goalFields.omit({dueDate:true}).shape,due_date:goalFields.shape.dueDate,version:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),archived:z.union([z.literal(0),z.literal(1)]),created_at:z.number().int().nonnegative().max(8640000000000000),updated_at:z.number().int().nonnegative().max(8640000000000000)}).strict();
const schema=z.object({version:z.literal(1),scope:z.literal('goals'),userId:z.string(),exportedAt:z.string().datetime(),goals:z.array(fields).max(10000)}).strict();
type GoalBackup=z.infer<typeof schema>;
const cols=Object.keys(fields.shape);
function validate(value:unknown){const parsed=schema.safeParse(value);if(!parsed.success)throw new BackupError('El respaldo de Metas contiene datos inválidos.');const b=parsed.data;if(new Set(b.goals.map(g=>g.id)).size!==b.goals.length||b.goals.some(g=>g.user_id!==b.userId))throw new BackupError('El respaldo de Metas tiene duplicados o registros de otra cuenta.');return b;}
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
function revision(b:GoalBackup){return hash([b.userId,b.goals.map(g=>Object.fromEntries(Object.entries(g).filter(([key])=>!['version','updated_at'].includes(key))))]);}
export function encodeGoals(b:GoalBackup){const literal=(v:unknown)=>typeof v==='number'?String(v):"'"+String(v).replaceAll("'","''")+"'";return [`-- MI_BALANCE_GOALS_V1 ${Buffer.from(JSON.stringify(b)).toString('base64')}`,`-- SHA256 ${hash(b)}`,'-- Respaldo de todas las metas activas y archivadas de Mi Balance.','BEGIN TRANSACTION;',...b.goals.map(g=>`INSERT OR IGNORE INTO financial_goals (${cols.join(', ')}) VALUES (${cols.map(c=>literal((g as Record<string,unknown>)[c])).join(', ')});`),'COMMIT;',''].join('\n');}
export function decodeGoals(sql:string){if(Buffer.byteLength(sql)>MAX_BACKUP_BYTES)throw new BackupError('El archivo supera los 4 MB.');const source=sql.replace(/^\uFEFF/,'');const match=/^-- MI_BALANCE_GOALS_V1 ([A-Za-z0-9+/=]+)\r?\n/.exec(source);if(!match)throw new BackupError('Selecciona un respaldo SQL descargado desde Metas.');let b:GoalBackup;try{b=validate(JSON.parse(Buffer.from(match[1],'base64').toString('utf8')));}catch(e){if(e instanceof BackupError)throw e;throw new BackupError('El archivo está dañado.');}if(encodeGoals(b).trim()!==source.trim())throw new BackupError('El archivo fue modificado o está dañado.');return b;}
export class GoalBackups{
 constructor(private db:DatabaseClient,private userId:string){}
 async read(){return validate({version:1,scope:'goals',userId:this.userId,exportedAt:new Date().toISOString(),goals:(await this.db.prepare(`SELECT ${cols.join(',')} FROM financial_goals WHERE user_id=? ORDER BY id`).bind(this.userId).all()).results});}
 authorize(b:GoalBackup){if(b.userId!==this.userId)throw new BackupError('Este respaldo pertenece a otra cuenta.',403);}
 async preview(b:GoalBackup){this.authorize(b);const current=await this.read();const counts=(b:GoalBackup)=>({goals:b.goals.length,obligations:0,movements:0,expenses:0,transfers:0});return {month:b.exportedAt.slice(0,7),exportedAt:b.exportedAt,records:counts(b),currentRecords:counts(current),revision:revision(current),adjacentMonths:[],totals:{available:b.goals.reduce((s,g)=>s+g.saved,0),pending:b.goals.reduce((s,g)=>s+Math.max(0,g.target-g.saved),0)}};}
 async restore(b:GoalBackup,expected:string){this.authorize(b);return this.db.transaction(async tx=>{const current=await new GoalBackups(tx,this.userId).read();if(revision(current)===revision(b))return {month:b.exportedAt.slice(0,7),unchanged:true};if(revision(current)!==expected)throw new BackupError('Las metas cambiaron después de la vista previa. Vuelve a revisar el archivo.',409);
  for(let offset=0;offset<b.goals.length;offset+=300){const ids=b.goals.slice(offset,offset+300).map(g=>g.id);if(await tx.prepare(`SELECT id FROM financial_goals WHERE user_id<>? AND id IN (${ids.map(()=>'?').join(',')}) LIMIT 1`).bind(this.userId,...ids).first())throw new BackupError('Una meta del archivo pertenece a otra cuenta.',409);}
  await tx.prepare('DELETE FROM financial_goals WHERE user_id=?').bind(this.userId).run();
  for(let offset=0;offset<b.goals.length;offset+=300)await tx.batch(b.goals.slice(offset,offset+300).map(g=>{const restored={...g,version:Math.max(g.version,current.goals.find(c=>c.id===g.id)?.version??0)+1,updated_at:Date.now()};return tx.prepare(`INSERT INTO financial_goals (${cols.join(',')}) VALUES (${cols.map(()=>'?').join(',')})`).bind(...cols.map(c=>(restored as Record<string,string|number>)[c]));}));return {month:b.exportedAt.slice(0,7),unchanged:false};});}
}
const headings=['ID','Meta','Objetivo (COP)','Ahorrado (COP)','Pendiente (COP)','Fecha objetivo','Estado','Icono','Color'];
const rows=(b:GoalBackup)=>b.goals.map(g=>[g.id,g.name,g.target,g.saved,Math.max(0,g.target-g.saved),g.due_date,g.archived?'Archivada':g.saved>=g.target?'Completada':'En progreso',g.icon,g.color]);
export function goalsCsv(b:GoalBackup){return '\uFEFF'+[headings,...rows(b)].map(row=>row.map(v=>{const text=typeof v==='string'&&/^\s*[=+\-@\t\r\n]/.test(v)?"'"+v:String(v);return '"'+text.replaceAll('"','""')+'"';}).join(',')).join('\r\n')+'\r\n';}
export async function goalsExcel(b:GoalBackup){const book=new ExcelJS.Workbook();book.creator='Mi Balance';book.created=new Date(b.exportedAt);const sheet=book.addWorksheet('Metas',{views:[{state:'frozen',ySplit:1}]});sheet.columns=headings.map((header,i)=>({header,width:i<2?40:23}));for(const row of rows(b)){const values=row.map((v,i)=>i===5?new Date(v+'T00:00:00Z'):v);sheet.addRow(values);}for(const col of [3,4,5])sheet.getColumn(col).numFmt='"$" #,##0';sheet.getColumn(6).numFmt='dd/mm/yyyy';sheet.autoFilter='A1:I1';sheet.getRow(1).height=28;sheet.getRow(1).eachCell(c=>{c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF252B50'}};});return new Uint8Array(await book.xlsx.writeBuffer());}
