'use client';
import { useEffect, useRef, useState } from 'react';
import PaymentReport, { PaymentDate } from './payment-report';
import FinanceChat from './finance-chat';
import NearbyPromotions from './nearby-promotions';
import VoiceExpenseRecorder from './voice-expense-recorder';
import { ArrowDownLeft, ArrowUpRight, Wallet, Plus, ChevronLeft, ChevronRight, Pencil, Search, CreditCard, Landmark, House, ShieldCheck, CircleCheck, X, RotateCcw, LoaderCircle, TriangleAlert, Utensils, Fuel, Wrench, School, ShoppingCart, Palmtree, Pill, Beer, ReceiptText, Trash2, Users, LogOut } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Progress } from '@/components/ui/progress';
import { Toaster, toast } from 'sonner';
import { dailyExpenseCategories, money, paidFor, status, totals, type DailyExpense, type Ledger, type Obligation } from '@/src/domain/finance';

const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const categories = ['Créditos','Tarjetas','Hogar','Seguros','Otros'];
const icons: Record<string, typeof Wallet> = {Créditos:Landmark,Tarjetas:CreditCard,Hogar:House,Seguros:ShieldCheck};
const expenseIcons: Record<string, typeof Wallet> = {'Restaurante':Utensils,'Gasolina':Fuel,'Mantenimiento de vehículo':Wrench,'Merienda escolar':School,'Mercado':ShoppingCart,'Paseo':Palmtree,'Medicina':Pill,'Cervezas':Beer,'Otros':ReceiptText};
type Editor = {kind:'income'|'payment'|'obligation'|'expense'; id:string; obligation?:Obligation; expense?:DailyExpense};
async function command(payload: unknown): Promise<Ledger> { const r = await fetch('/api/ledger',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const result = await r.json() as Ledger & {error?:string}; if(!r.ok) throw new Error(result.error ?? 'No se pudo completar la operación.'); return result; }
export default function Dashboard({user,onLogout,onAdmin}:{user:{displayName:string;role:'admin'|'user'};onLogout:()=>void;onAdmin:()=>void}) {
 const [reportDate,setReportDate] = useState(today);
 useEffect(() => { const timer=setInterval(()=>setReportDate(today()),60000); return ()=>clearInterval(timer); },[]);
 const [month,setMonth] = useState('2026-09'); const [ledger,setLedger] = useState<Ledger>({obligations:[],movements:[],expenses:[]});
 const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [saving,setSaving] = useState(false);
 const [reportRevision,setReportRevision] = useState(0);
 function applySavedLedger(data: Ledger) {
  setLedger(data);
 setReportDate(today());
 setReportRevision(value=>value+1);
 setFilter('Todas');
  setExpenseFilter('Todas');
 }
 const [activeTab,setActiveTab] = useState('obligations'); const [query,setQuery] = useState(''); const [filter,setFilter] = useState('Todas'); const [expenseFilter,setExpenseFilter] = useState('Todas'); const [editor,setEditor] = useState<Editor|null>(null); const [remove,setRemove] = useState<string|null>(null); const [removeExpense,setRemoveExpense] = useState<string|null>(null);
 const [category,setCategory] = useState('Créditos'); const [expenseCategory,setExpenseCategory] = useState<(typeof dailyExpenseCategories)[number]>('Restaurante'); const [formError,setFormError] = useState(''); const [reload,setReload] = useState(0); const formRef = useRef<HTMLFormElement>(null);
 useEffect(() => { setMonth(today().slice(0,7)); },[]);
 useEffect(() => { let active=true; setLoading(true);setError(''); command({action:'initialize',month}).then(data => {if(active)setLedger(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}; },[month,reload]);
 useEffect(() => {
  const context = (document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;
  if(!context) return; const lifecycle=new AbortController();
  Promise.resolve(context.registerTool({name:'read_monthly_balance',description:'Consulta las obligaciones, ingresos, pagos y gastos diarios visibles del mes seleccionado.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input || typeof input!=='object' || Object.keys(input).length)throw new Error('No se aceptan parámetros'); if(loading || error)throw new Error('Los datos no están disponibles');return {month,...ledger,totals:totals(ledger)};}},{signal:lifecycle.signal})).catch(()=>{});
  return()=>lifecycle.abort();
 },[ledger,month,loading,error]);
 const selectedMovement = ledger.movements.find(m => m.id === remove);
 const selectedExpense = ledger.expenses.find(e=>e.id===removeExpense);
 const reversingPayment = selectedMovement?.kind === 'payment';
 const selectedMovementName = selectedMovement?.kind === 'payment' ? ledger.obligations.find(o=>o.id===selectedMovement.obligationId)?.name ?? selectedMovement.description : selectedMovement?.description;
 const sums=totals(ledger); const completed=ledger.obligations.filter(o=>status(o,ledger.movements)==='Pagado').length; const missing=ledger.obligations.filter(o=>o.amount===null).length;
 const visible=ledger.obligations.filter(o=>o.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (filter==='Todas'||status(o,ledger.movements)===filter));
 const visibleExpenses=ledger.expenses.filter(e=>expenseFilter==='Todas'||e.category===expenseFilter);
 function shift(delta:number){const d=new Date(month+'-15T12:00:00');d.setMonth(d.getMonth()+delta);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)}
 function open(kind:Editor['kind'],obligation?:Obligation,expense?:DailyExpense){setEditor({kind,id:kind==='obligation'&&obligation?obligation.id:kind==='expense'&&expense?expense.id:crypto.randomUUID(),obligation,expense});setCategory(obligation?.category??'Créditos');setExpenseCategory(expense?.category??'Restaurante');setFormError('')}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!editor || saving)return; const f=new FormData(event.currentTarget); setSaving(true);setFormError('');
  const payload=editor.kind==='obligation'?{action:'obligation',applyFutureAmount:['Créditos','Tarjetas'].includes(category)&&f.get('applyFutureAmount')==='on',id:editor.id,month,name:f.get('name'),category,amount:f.get('amount')===''?null:Number(f.get('amount')),note:f.get('note')??'',cutoffDay:f.get('cutoffDay')===''?null:Number(f.get('cutoffDay')),dueDay:f.get('dueDay')===''?null:Number(f.get('dueDay')),totalDebt:f.get('totalDebt')===''?null:Number(f.get('totalDebt')),bank:f.get('bank')??'',bankingUrl:f.get('bankingUrl')??'',interestMV:f.get('interestMV')===''?null:Number(f.get('interestMV')),interestEA:f.get('interestEA')===''?null:Number(f.get('interestEA'))}:editor.kind==='expense'?{action:'expense',id:editor.id,month,category:expenseCategory,amount:Number(f.get('amount')),date:f.get('date'),description:f.get('description')}:{action:'movement',id:editor.id,month,kind:editor.kind,obligationId:editor.obligation?.id??null,amount:Number(f.get('amount')),date:f.get('date'),description:f.get('description')};
  try{applySavedLedger(await command(payload));setEditor(null);toast.success('Registro guardado');}catch(e){setFormError((e as Error).message)}finally{setSaving(false)}
 }
 const monthLabel=new Intl.DateTimeFormat('es-CO',{month:'long',year:'numeric'}).format(new Date(month+'-15T12:00:00'));
 return <div className="app-shell"><Toaster position="top-right" richColors/>
  <header className="topbar"><a href="/" className="brand"><span className="brand-symbol"><Wallet size={22}/></span>mi balance<span className="brand-dot">.</span></a><span className="top-label">FINANZAS PERSONALES</span><div className="account-actions"><span className="account-name"><ShieldCheck size={16}/>{user.displayName}</span>{user.role==='admin'&&<button onClick={onAdmin}><Users size={16}/> Administrar usuarios</button>}<button onClick={onLogout}><LogOut size={16}/> Cerrar sesión</button></div></header>
  <main className="workspace"><div className="page-heading"><div><p className="eyebrow">TU MES, EN ORDEN</p><h1>Control mensual</h1><p className="muted">Cada ingreso tiene un propósito. Cada pago, su lugar.</p></div><div className="heading-actions"><div className="month-picker"><button aria-label="Mes anterior" disabled={loading||saving} onClick={()=>shift(-1)}><ChevronLeft size={18}/></button><label><span className="sr-only">Mes</span><input type="month" value={month} disabled={saving} onChange={e=>{if(/^20\d{2}-(0[1-9]|1[0-2])$/.test(e.target.value))setMonth(e.target.value)}}/></label><button aria-label="Mes siguiente" disabled={loading||saving} onClick={()=>shift(1)}><ChevronRight size={18}/></button></div><button className="primary" disabled={loading||!!error} onClick={()=>open('income')}><Plus size={18}/> Registrar ingreso</button></div></div>
  {error ? <div className="error" role="alert">{error}<button className="secondary" onClick={()=>setReload(x=>x+1)}>Reintentar</button></div> : <>
  <section className="summary" aria-label="Resumen mensual"><div className="available"><div className="metric-label"><span>Disponible del mes</span><Wallet size={20}/></div><strong>{loading?'—':money(sums.available)}</strong><p>Ingresos menos pagos y gastos diarios</p><div className="available-bottom"><span>Saldo para tus próximos pagos</span><ArrowUpRight size={20}/></div></div><div className="metric"><span className="metric-icon income"><ArrowDownLeft size={21}/></span><p>Ingresos recibidos</p><strong>{loading?'—':money(sums.income)}</strong><small>{ledger.movements.filter(m=>m.kind==='income').length} ingresos registrados</small></div><div className="metric"><span className="metric-icon paid"><CircleCheck size={21}/></span><p>Total pagado</p><strong>{loading?'—':money(sums.paid)}</strong><small>{completed} de {ledger.obligations.length} obligaciones al día</small></div><div className="metric"><span className="metric-icon expenses"><ReceiptText size={21}/></span><p>Gastos diarios</p><strong>{loading?'—':money(sums.dailyExpenses)}</strong><small>{ledger.expenses.length} gastos registrados</small></div><div className="metric"><span className="metric-icon pending"><CreditCard size={21}/></span><p>Saldo pendiente</p><strong>{loading?'—':money(sums.pending)}</strong><small>{missing ? `${missing} valores por definir, no incluidos` : 'Todas las obligaciones tienen valor'}</small></div></section>
  <div className="content-grid"><section className="ledger-panel"><Tabs value={activeTab} onValueChange={setActiveTab}><div className="panel-tabs"><TabsList variant="line" aria-label="Secciones del control mensual"><div className="tab-cluster obligation-flow" data-active={['obligations','movements','report'].includes(activeTab)}><span className="tab-cluster-label"><Landmark size={14}/> GESTIÓN DE OBLIGACIONES</span><div className="tab-cluster-items"><TabsTrigger value="obligations"><span className="flow-step">1</span> Obligaciones <span className="count">{ledger.obligations.length}</span></TabsTrigger><TabsTrigger value="movements"><span className="flow-step">2</span> Movimientos</TabsTrigger><TabsTrigger value="report"><span className="flow-step">3</span> Reporte de pagos</TabsTrigger></div></div><div className="tab-cluster monthly-tools" data-active={['expenses','promotions'].includes(activeTab)}><span className="tab-cluster-label">HERRAMIENTAS DEL MES</span><div className="tab-cluster-items"><TabsTrigger value="expenses">Gastos diarios <span className="count">{ledger.expenses.length}</span></TabsTrigger><TabsTrigger value="promotions">Promociones</TabsTrigger></div></div><div className="tab-cluster advisor-tool" data-active={activeTab==='coach'}><span className="tab-cluster-label">ASESORÍA FINANCIERA</span><div className="tab-cluster-items"><TabsTrigger value="coach">Asistente IA</TabsTrigger></div></div></TabsList>{activeTab==='obligations'?<button className="text-button" disabled={loading} onClick={()=>open('obligation')}><Plus size={17}/> Nueva obligación</button>:activeTab==='expenses'?<button className="text-button" disabled={loading} onClick={()=>open('expense')}><Plus size={17}/> Nuevo gasto</button>:null}</div>
   <TabsContent value="obligations"><div className="table-toolbar"><label className="search"><Search size={17}/><input aria-label="Buscar obligación" placeholder="Buscar una obligación…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filtrar por estado"><SelectValue/></SelectTrigger><SelectContent>{['Todas','Pendiente','Parcial','Pagado','Sin valor'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>
   {loading?<div className="empty"><LoaderCircle className="spin"/> Cargando tus obligaciones…</div>:<Table><TableHeader><TableRow><TableHead>Obligación</TableHead><TableHead className="numeric">Valor / pagado</TableHead><TableHead>Fechas</TableHead><TableHead>Estado</TableHead><TableHead className="numeric">Acciones</TableHead></TableRow></TableHeader><TableBody>{visible.map(o=>{const state=status(o,ledger.movements);const Icon=icons[o.category]??Wallet;const paid=paidFor(o.id,ledger.movements);return <TableRow key={o.id}><TableCell><div className="obligation-name"><span className={'category-icon '+o.category}><Icon size={18}/></span><div><strong>{o.name}</strong><small>{o.category}{o.bank?` · ${o.bank}`:""}</small><details className="obligation-details"><summary>Datos de la deuda</summary><div><span>Total deuda: <b>{o.totalDebt==null?"Por definir":money(o.totalDebt)}</b></span><span>Banco: {o.bank||"Por definir"}</span><span>M.V.: {o.interestMV==null?"Por definir":`${o.interestMV}%`} · E.A.: {o.interestEA==null?"Por definir":`${o.interestEA}%`}</span>{o.bankingUrl&&<a href={o.bankingUrl} target="_blank" rel="noopener noreferrer">Abrir banca virtual ↗</a>}</div></details></div></div></TableCell><TableCell className="numeric amount">{o.amount===null?'Por definir':money(o.amount)}<small>{paid>0?`${money(paid)} pagado`:'Sin pagos'}</small></TableCell><TableCell><div className="obligation-dates"><span>Corte{o.cutoffDay?` (día ${o.cutoffDay})`:''}: <b>{o.cutoffDate?o.cutoffDate.split('-').reverse().join('/'):'Por definir'}</b></span><span>Límite de pago{o.dueDay?` (día ${o.dueDay})`:''}: <b>{o.dueDate?o.dueDate.split('-').reverse().join('/'):'Por definir'}</b></span><PaymentDate obligation={o} movements={ledger.movements}/></div></TableCell><TableCell><span className={'status '+state.replace(' ','-')}>{state}</span></TableCell><TableCell><div className="row-actions">{state!=='Pagado' && <button className="pay-button" onClick={()=>open(o.amount===null?'obligation':'payment',o)}>{o.amount===null?'Definir':'Pagar'}</button>}<button className="icon-button" aria-label={'Editar '+o.name} onClick={()=>open('obligation',o)}><Pencil size={15}/></button></div></TableCell></TableRow>})}</TableBody></Table>}
   {!loading && !visible.length && <div className="empty">No hay obligaciones que coincidan con tu búsqueda.</div>}<footer className="table-footer"><span>{visible.length} obligaciones · Valores en COP</span><span>Total definido <b>{money(sums.committed)}</b></span></footer></TabsContent>
   <TabsContent value="expenses"><div className="expense-heading"><div><h2>Gastos diarios de {monthLabel}</h2><p>Registra tus consumos cotidianos para conocer el dinero realmente disponible.</p></div><div className="expense-total"><span>Total del mes</span><strong>{money(sums.dailyExpenses)}</strong></div></div><VoiceExpenseRecorder month={month} disabled={loading||saving} onSave={async expenses=>{applySavedLedger(await command({action:'expenses',month,expenses:expenses.map(expense=>({...expense,id:crypto.randomUUID()}))}));toast.success(expenses.length===1?'Gasto registrado por voz.':'Gastos registrados por voz.')}}/><div className="expense-toolbar"><span>{visibleExpenses.length} de {ledger.expenses.length} registros</span><Select value={expenseFilter} onValueChange={setExpenseFilter}><SelectTrigger aria-label="Filtrar gastos por categoría"><SelectValue/></SelectTrigger><SelectContent>{['Todas',...dailyExpenseCategories].map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div>{loading?<div className="empty"><LoaderCircle className="spin"/> Cargando tus gastos…</div>:ledger.expenses.length===0?<div className="empty expense-empty"><ReceiptText size={30}/><h3>Aún no hay gastos diarios</h3><p>Agrega restaurante, gasolina, mercado, medicina u otros consumos del mes.</p><button className="primary" onClick={()=>open('expense')}><Plus size={17}/> Registrar primer gasto</button></div>:visibleExpenses.length===0?<div className="empty">No hay gastos en esta categoría.</div>:<div className="expense-list">{visibleExpenses.map(expense=>{const ExpenseIcon=expenseIcons[expense.category]??ReceiptText;return <article className="expense-item" key={expense.id}><span className="expense-icon"><ExpenseIcon size={19}/></span><div className="expense-description"><strong>{expense.description}</strong><small>{expense.category} · {expense.date.split('-').reverse().join('/')}</small></div><b>−{money(expense.amount)}</b><div className="expense-actions"><button className="icon-button" aria-label={'Editar gasto '+expense.description} onClick={()=>open('expense',undefined,expense)}><Pencil size={16}/></button><button className="expense-delete" aria-label={'Eliminar gasto '+expense.description} onClick={()=>setRemoveExpense(expense.id)}><Trash2 size={16}/></button></div></article>})}</div>}<footer className="table-footer"><span>Los gastos diarios descuentan el disponible del mes.</span><span>Total <b>{money(sums.dailyExpenses)}</b></span></footer></TabsContent>
   <TabsContent value="promotions"><NearbyPromotions active={activeTab==='promotions'}/></TabsContent>
   <TabsContent value="coach"><FinanceChat key={month} month={month} monthLabel={monthLabel} ledger={ledger}/></TabsContent>
   <TabsContent value="report"><PaymentReport key={month+':'+reportRevision} ledger={ledger} today={reportDate} monthLabel={monthLabel} loading={loading}/></TabsContent>
   <TabsContent value="movements"><div className="movement-heading"><h2>Historial de {monthLabel}</h2><p className="muted">Ingresos y abonos registrados, con su fecha de pago.</p></div>{ledger.movements.length===0?<div className="empty"><Wallet size={28}/><h3>Aún no hay movimientos</h3><p>Registra tu primer ingreso o el pago de una obligación.</p><button className="primary" onClick={()=>open('income')}>Registrar ingreso</button></div>:ledger.movements.map(m=><div className="movement" key={m.id}><span className={'metric-icon '+(m.kind==='income'?'income':'paid')}>{m.kind==='income'?<ArrowDownLeft size={20}/>:<ArrowUpRight size={20}/>}</span><div className="movement-description"><strong>{m.kind==='income'?m.description:ledger.obligations.find(o=>o.id===m.obligationId)?.name}</strong><small>{m.date?m.date.split('-').reverse().join('/'):'Fecha no informada en la imagen'} · {m.description}</small></div><b className={m.kind==='income'?'green':''}>{m.kind==='income'?'+':'−'}{money(m.amount)}</b><button className="reverse-button" disabled={saving} aria-label={(m.kind==='payment'?'Reversar pago de ':'Eliminar ingreso ')+(ledger.obligations.find(o=>o.id===m.obligationId)?.name??m.description)+' por '+money(m.amount)} onClick={()=>setRemove(m.id)}>{m.kind==='payment'?<RotateCcw size={16}/>:<X size={16}/>} {m.kind==='payment'?'Reversar pago':'Eliminar ingreso'}</button></div>)}</TabsContent>
  </Tabs></section><aside className="right-rail"><section className="progress-card"><div className="rail-heading"><h2>Así va tu mes</h2><span className="month-short">{month.slice(5)}/{month.slice(0,4)}</span></div><div className="progress-number">{sums.committed?Math.round(sums.paid/sums.committed*100):0}<span>%</span></div><p className="muted">del valor de tus obligaciones pagado</p><Progress value={sums.committed?sums.paid/sums.committed*100:0} aria-label="Porcentaje pagado" className="month-progress"/><div className="progress-caption"><span>{completed} pagadas</span><span>{ledger.obligations.length-completed} por resolver</span></div><hr/><h3>Distribución del mes</h3>{categories.map(c=>{const total=ledger.obligations.filter(o=>o.category===c).reduce((s,o)=>s+(o.amount??0),0);return total>0&&<div className="category-summary" key={c}><span>{c}</span><b>{money(total)}</b></div>})}</section><section className="note-card"><span className="note-icon"><Landmark size={20}/></span><h3>Cuando llegue tu ingreso</h3><p>Regístralo y elige una obligación para pagar. También puedes abonar una parte y completar el saldo después.</p></section>{missing>0&&<div className="missing-note"><b>{missing} valores por completar</b><p>Abre «Definir» para incluir estas obligaciones en tu presupuesto.</p></div>}{sums.available<0&&<div className="missing-note"><b>Faltan ingresos por registrar</b><p>Los pagos superan los ingresos anotados en este mes.</p></div>}<p className="source-note">Datos iniciales de tu imagen de agosto de 2026. Los nuevos meses conservan las obligaciones y comienzan sin pagos.</p></aside></div></>}
  <footer className="page-footer"><span>mi balance.</span><span>Un mes a la vez.</span></footer></main>
  <Dialog open={!!editor} onOpenChange={v=>{if(!v&&!saving)setEditor(null)}}><DialogContent className="editor"><DialogTitle>{editor?.kind==='income'?'Registrar ingreso':editor?.kind==='payment'?'Registrar pago':editor?.kind==='expense'?(editor.expense?'Editar gasto diario':'Nuevo gasto diario'):editor?.obligation?'Editar obligación':'Nueva obligación'}</DialogTitle><DialogDescription>{editor?.kind==='payment'?editor.obligation?.name:editor?.kind==='income'?'Anota el dinero que recibiste de tu trabajo.':editor?.kind==='expense'?'Registra un consumo del día. Este valor se descontará del disponible mensual.':'Configura una vez los días de corte y pago, banco y datos de la deuda. Se conservan desde este mes hacia adelante; los meses anteriores no cambian.'}</DialogDescription>{editor&&<form key={editor.id} ref={formRef} onSubmit={submit}>
   {editor.kind==='obligation'?<><label>Nombre<input name="name" required maxLength={120} defaultValue={editor.obligation?.name}/></label><label>Categoría<Select value={category} onValueChange={setCategory}><SelectTrigger className="category-select-trigger" aria-label="Categoría"><SelectValue/></SelectTrigger><SelectContent className="category-select-menu" position="popper" align="start" sideOffset={6}>{categories.map(c=>{const CategoryIcon=icons[c]??Wallet;return <SelectItem key={c} value={c}><CategoryIcon size={17}/><span>{c}</span></SelectItem>})}</SelectContent></Select></label></>:editor.kind==='expense'?<><label>Categoría<Select value={expenseCategory} onValueChange={value=>setExpenseCategory(value as (typeof dailyExpenseCategories)[number])}><SelectTrigger className="category-select-trigger" aria-label="Categoría del gasto"><SelectValue/></SelectTrigger><SelectContent className="category-select-menu" position="popper" align="start" sideOffset={6}>{dailyExpenseCategories.map(c=>{const ExpenseIcon=expenseIcons[c]??ReceiptText;return <SelectItem key={c} value={c}><ExpenseIcon size={17}/><span>{c}</span></SelectItem>})}</SelectContent></Select></label><label>Descripción<input name="description" required maxLength={160} placeholder="Ej. Almuerzo familiar" defaultValue={editor.expense?.description}/></label></>:<label>Descripción<input name="description" required maxLength={160} defaultValue={editor.kind==='income'?'Ingreso de trabajo':'Pago de obligación'}/></label>}
   <label>{editor.kind==='payment'?'Valor del abono (COP)':editor.kind==='obligation'?'Cuota de este mes (COP)':editor.kind==='expense'?'Valor del gasto (COP)':'Valor (COP)'}<input name="amount" type="number" min="1" max={editor.kind==='payment'?(editor.obligation!.amount??0)-paidFor(editor.obligation!.id,ledger.movements):999999999999} step="1" required={editor.kind!=='obligation'} placeholder={editor.kind==='expense'?'Ej. 35000':'Ej. 1500000'} defaultValue={editor.kind==='obligation'?editor.obligation?.amount??'':editor.kind==='payment'?(editor.obligation!.amount??0)-paidFor(editor.obligation!.id,ledger.movements):editor.kind==='expense'?editor.expense?.amount??'':''}/></label>
   {editor.kind==='obligation'&&editor.obligation&&['Créditos','Tarjetas'].includes(category)&&<div className="future-amount-option"><label><input type="checkbox" name="applyFutureAmount"/><span>Actualizar también el valor de la cuota en los meses siguientes</span></label><small>Sin marcar: cambia solo la cuota de {monthLabel}. Marcado: aplica a los meses siguientes existentes y a los nuevos. Los pagos ya registrados se conservan; no se permite una cuota menor que lo pagado.</small></div>}
   {editor.kind==='obligation'?<><small className="muted">Deja el valor vacío si todavía no lo conoces.</small><fieldset className="obligation-settings"><legend>Fechas de cada mes</legend><div className="date-fields"><label>Día de corte<input name="cutoffDay" type="number" min="1" max="31" step="1" placeholder="Ej. 25" defaultValue={editor.obligation?.cutoffDay??(editor.obligation?.cutoffDate?Number(editor.obligation.cutoffDate.slice(-2)):'')}/></label><label>Día límite de pago<input name="dueDay" type="number" min="1" max="31" step="1" placeholder="Ej. 10" defaultValue={editor.obligation?.dueDay??(editor.obligation?.dueDate?Number(editor.obligation.dueDate.slice(-2)):'')}/></label></div><small className="muted">Días del 1 al 31, opcionales. Se repiten cada mes. Si el día no existe, se usa el último día del mes. Ambas fechas corresponden al mes mostrado; la fecha de pago realizado se registra al abonar.</small></fieldset>
   <fieldset className="obligation-settings"><legend>Deuda y entidad</legend><label>Total de la deuda (COP)<input name="totalDebt" type="number" min="0" max="999999999999" step="1" placeholder="Saldo del último extracto" defaultValue={editor.obligation?.totalDebt??''}/></label><small className="muted">Saldo informado por ti. No se descuenta automáticamente con las cuotas: pueden incluir intereses y otros cargos.</small><label>Banco<input name="bank" maxLength={120} placeholder="Nombre del banco o entidad" defaultValue={editor.obligation?.bank??''}/></label><label>Link de banca virtual<input name="bankingUrl" type="url" maxLength={500} pattern="https://.*" placeholder="https://…" defaultValue={editor.obligation?.bankingUrl??''}/></label><div className="date-fields"><label>Interés M.V. (%)<input name="interestMV" type="number" min="0" max="100000" step="any" placeholder="Ej. 1.5" defaultValue={editor.obligation?.interestMV??''}/></label><label>Interés E.A. (%)<input name="interestEA" type="number" min="0" max="100000" step="any" placeholder="Ej. 19.56" defaultValue={editor.obligation?.interestEA??''}/></label></div><small className="muted">M.V.: mes vencido. E.A.: efectivo anual. Registra las tasas de tu extracto; no se convierten automáticamente. Puedes dejar desconocidos los campos vacíos.</small></fieldset><label>Nota opcional<input name="note" maxLength={300} defaultValue={editor.obligation?.note}/></label></>:<label>Fecha<input name="date" type="date" required min={month+'-01'} max={month+'-'+new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()} defaultValue={editor.kind==='expense'&&editor.expense?editor.expense.date:today().startsWith(month)?today():month+'-01'}/></label>}
   {formError&&<p className="error" role="alert">{formError}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>setEditor(null)}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Guardando…':'Guardar registro'}</button></div></form>}</DialogContent></Dialog>
  <AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!saving)setRemove(null)}}><AlertDialogContent className="movement-confirm-dialog"><AlertDialogHeader><div className="confirm-dialog-heading"><span className="confirm-dialog-icon" aria-hidden="true"><TriangleAlert size={22}/></span><div><AlertDialogTitle>{reversingPayment?'¿Reversar este pago?':'¿Eliminar este ingreso?'}</AlertDialogTitle><p className="confirm-dialog-lead">Revisa el movimiento antes de continuar.</p></div></div><AlertDialogDescription asChild><div><div className="confirm-movement-summary"><span>{selectedMovementName}</span><strong>{selectedMovement?money(selectedMovement.amount):''}</strong><small>{selectedMovement?.date?selectedMovement.date.split('-').reverse().join('/'):'Fecha no informada'}</small></div><p>{reversingPayment?'Se eliminará únicamente este pago o abono. Su valor volverá al saldo pendiente y se actualizarán el disponible y el reporte. Los demás abonos se conservarán.':'Se eliminará este ingreso y se recalculará el dinero disponible del mes.'}</p>{reversingPayment&&<p className="confirm-dialog-note">Esta acción solo corrige el registro en Mi Balance; no revierte una transferencia bancaria.</p>}</div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={saving}>Cancelar</AlertDialogCancel><AlertDialogAction className="danger-action" disabled={saving} onClick={async e=>{e.preventDefault();setSaving(true);try{applySavedLedger(await command({action:'removeMovement',month,id:remove}));setRemove(null);toast.success(reversingPayment?'Pago reversado. Saldos y reporte actualizados.':'Ingreso eliminado')}catch(e){toast.error((e as Error).message)}finally{setSaving(false)}}}>{saving?'Procesando…':reversingPayment?'Sí, reversar pago':'Sí, eliminar ingreso'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <AlertDialog open={!!removeExpense} onOpenChange={v=>{if(!v&&!saving)setRemoveExpense(null)}}><AlertDialogContent className="movement-confirm-dialog"><AlertDialogHeader><div className="confirm-dialog-heading"><span className="confirm-dialog-icon" aria-hidden="true"><TriangleAlert size={22}/></span><div><AlertDialogTitle>¿Eliminar este gasto?</AlertDialogTitle><p className="confirm-dialog-lead">Revisa el registro antes de continuar.</p></div></div><AlertDialogDescription asChild><div><div className="confirm-movement-summary"><span>{selectedExpense?.description}</span><strong>{selectedExpense?money(selectedExpense.amount):''}</strong><small>{selectedExpense?`${selectedExpense.category} · ${selectedExpense.date.split('-').reverse().join('/')}`:''}</small></div><p>Se eliminará el gasto y se recalculará inmediatamente el dinero disponible del mes.</p></div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={saving}>Cancelar</AlertDialogCancel><AlertDialogAction className="danger-action" disabled={saving} onClick={async e=>{e.preventDefault();if(!removeExpense)return;setSaving(true);try{applySavedLedger(await command({action:'removeExpense',month,id:removeExpense}));setRemoveExpense(null);toast.success('Gasto eliminado. Disponible actualizado.')}catch(e){toast.error((e as Error).message)}finally{setSaving(false)}}}>{saving?'Procesando…':'Sí, eliminar gasto'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
