import { z } from 'zod';
import { GoalBackups,decodeGoals,encodeGoals,goalsCsv,goalsExcel } from '@/src/infrastructure/goal-backups';
import { BackupError,MAX_BACKUP_BYTES } from '@/src/domain/month-backup';
import { database,DatabaseError } from '@/src/infrastructure/database';
import { AuthError,D1AuthRepository } from '@/src/infrastructure/d1-auth';
import { isAllowedOrigin } from '@/src/infrastructure/request-origin';
export const runtime='nodejs';
const headers={'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'};
async function repo(r:Request){const db=database();const user=await new D1AuthRepository(db).requireUser(r);return new GoalBackups(db,user.id);}
function failure(e:unknown){const known=e instanceof BackupError||e instanceof AuthError;return Response.json({error:known?e.message:e instanceof DatabaseError?e.message:'No se pudo procesar el respaldo de Metas. Revisa el archivo e intenta nuevamente.'},{status:known?e.status:e instanceof DatabaseError?503:400,headers});}
export async function GET(r:Request){try{const repository=await repo(r);const format=z.enum(['xlsx','csv','sql']).parse(new URL(r.url).searchParams.get('format'));const b=await repository.read();const data=format==='sql'?encodeGoals(b):format==='csv'?goalsCsv(b):await goalsExcel(b);if(format==='sql'&&Buffer.byteLength(data as string)>MAX_BACKUP_BYTES)throw new BackupError('El respaldo supera los 4 MB.');return new Response(typeof data==='string'?data:new Uint8Array(data),{headers:{...headers,'Content-Type':{sql:'application/sql; charset=utf-8',csv:'text/csv; charset=utf-8',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}[format],'Content-Disposition':`attachment; filename="mi-balance-metas.${format}"`}});}catch(e){return failure(e);}}
export async function POST(r:Request){if(!isAllowedOrigin(r))return Response.json({error:'Origen no permitido'},{status:403,headers});try{const repository=await repo(r);const reader=r.body?.getReader();if(!reader)throw new BackupError('Selecciona un respaldo.');let length=0;const chunks:Uint8Array[]=[];try{while(true){const part=await reader.read();if(part.done)break;length+=part.value.byteLength;if(length>MAX_BACKUP_BYTES+512*1024){await reader.cancel();throw new BackupError('El archivo supera los 4 MB.',413);}chunks.push(part.value);}}finally{reader.releaseLock();}
 const input=z.object({action:z.enum(['preview','restore']),sql:z.string().max(MAX_BACKUP_BYTES),revision:z.string().regex(/^[a-f0-9]{64}$/).optional()}).strict().parse(JSON.parse(Buffer.concat(chunks).toString('utf8')));const b=decodeGoals(input.sql);if(input.action==='preview')return Response.json(await repository.preview(b),{headers});if(!input.revision)throw new BackupError('Revisa primero la vista previa.');return Response.json(await repository.restore(b,input.revision),{headers});}catch(e){return failure(e);}}
