import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { projectRoot } from './sites-env.mjs';
const args=['--import','./scripts/sites-env.mjs',fileURLToPath(new URL('../node_modules/wrangler/bin/wrangler.js',import.meta.url)),'dev','--config','dist/server/wrangler.json','--local','--persist-to','.wrangler/state','--ip','127.0.0.1','--inspector-port','0'];
if(existsSync('.env.local'))args.push('--env-file',fileURLToPath(new URL('../.env.local',import.meta.url)));
const child=spawn(process.execPath,[...args,...process.argv.slice(2)],{cwd:projectRoot,stdio:'inherit'});
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>child.kill(signal));
child.on('error',()=>{console.error('No se pudo iniciar la plataforma local.');process.exitCode=1});
child.on('exit',code=>{process.exitCode=code??0});
