import {readFileSync,mkdirSync,writeFileSync,readdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import ts from 'typescript';
const output=resolve('.sites-runtime/auth-tests');
for(const file of ['domain/auth','domain/finance','domain/seed','infrastructure/d1-auth','infrastructure/d1-ledger']){const source=readFileSync(resolve('src',file+'.ts'),'utf8');const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace(/from '(\.\.?\/[^']+)'/g,"from '$1.js'");mkdirSync(dirname(resolve(output,file+'.js')),{recursive:true});writeFileSync(resolve(output,file+'.js'),js)}
const {D1AuthRepository,sessionCookie}=await import(pathToFileURL(resolve(output,'infrastructure/d1-auth.js')));
const {D1LedgerRepository}=await import(pathToFileURL(resolve(output,'infrastructure/d1-ledger.js')));
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync('drizzle').filter(file=>file.endsWith('.sql')).sort())sqlite.exec(readFileSync(resolve('drizzle',file),'utf8'));
function prepare(sql,args=[]){return {bind(...values){return prepare(sql,values)},async first(){return sqlite.prepare(sql).get(...args)??null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const result=sqlite.prepare(sql).run(...args);return {results:[],meta:{changes:result.changes}}},sql,args}}
const db={prepare,async batch(statements){sqlite.exec('BEGIN');try{const rows=statements.map(statement=>{if(/^SELECT/i.test(statement.sql.trim()))return {results:sqlite.prepare(statement.sql).all(...statement.args)};const result=sqlite.prepare(statement.sql).run(...statement.args);return {results:[],meta:{changes:result.changes}}});sqlite.exec('COMMIT');return rows}catch(error){sqlite.exec('ROLLBACK');throw error}}};
let now=Date.parse('2026-09-24T12:00:00-05:00');const auth=new D1AuthRepository(db,()=>now);
const adminId=await auth.bootstrap('Admin@Example.com','Administradora Principal','Segura2026Clave');assert.equal(await auth.countUsers(),1);
const adminLogin=await auth.login('admin@example.com','Segura2026Clave');const adminRequest=new Request('http://localhost/',{headers:{cookie:sessionCookie(adminLogin.token,new Request('http://localhost/')).split(';')[0]}});assert.equal((await auth.requireAdmin(adminRequest)).id,adminId);
const userId=await auth.createUser('persona@example.com','Persona Usuaria','Usuario2026Clave','user','pending');const verification=await auth.createEmailVerification(userId);await assert.rejects(()=>auth.login('persona@example.com','Usuario2026Clave'),/Confirma/);await assert.rejects(()=>auth.setStatus(adminId,userId,'active'),/Valida/);await auth.verifyEmail(verification);await assert.rejects(()=>auth.verifyEmail(verification),/no es válido/);await assert.rejects(()=>auth.login('persona@example.com','Usuario2026Clave'),/pendiente/);await auth.setStatus(adminId,userId,'active');
const userLogin=await auth.login('persona@example.com','Usuario2026Clave');const userRequest=new Request('http://localhost/',{headers:{cookie:sessionCookie(userLogin.token,new Request('http://localhost/')).split(';')[0]}});assert.equal((await auth.requireUser(userRequest)).id,userId);await assert.rejects(()=>auth.requireAdmin(userRequest),/administradora/);
const adminLedger=new D1LedgerRepository(db,adminId,false),userLedger=new D1LedgerRepository(db,userId,false);await adminLedger.saveObligation({id:crypto.randomUUID(),month:'2026-09',name:'Solo administración',category:'Otros',amount:100,note:'',cutoffDate:null,dueDate:null});assert.equal((await adminLedger.read('2026-09')).obligations.length,1);assert.equal((await userLedger.read('2026-09')).obligations.length,0);
await auth.requestReset('persona@example.com');const reset=(await auth.listResets())[0];const code=await auth.issueReset(adminId,reset.id);await auth.resetPassword(code,'Nueva2026Clave');assert.equal(await auth.session(userRequest),null);await assert.rejects(()=>auth.resetPassword(code,'Otra2026Clave'),/no es válido/);await assert.rejects(()=>auth.login('persona@example.com','Usuario2026Clave'),/incorrectos/);assert.equal((await auth.login('persona@example.com','Nueva2026Clave')).user.id,userId);
const manualId=await auth.createUser('manual@example.com','Validación Manual','Manual2026Clave','user','pending');await auth.markEmailVerified(adminId,manualId);await auth.setStatus(adminId,manualId,'active');assert.equal((await auth.login('manual@example.com','Manual2026Clave')).user.emailVerifiedAt,now);
const firebaseId=await auth.createFirebaseUser('firebase@example.com','Cuenta Firebase','firebase-uid');await assert.rejects(()=>auth.loginFirebase({uid:'firebase-uid',email:'firebase@example.com',emailVerified:false}),/Confirma/);await auth.loginFirebase({uid:'firebase-uid',email:'firebase@example.com',emailVerified:true}).catch(error=>assert.match(error.message,/pendiente/));await auth.setStatus(adminId,firebaseId,'active');assert.equal((await auth.loginFirebase({uid:'firebase-uid',email:'firebase@example.com',emailVerified:true})).user.id,firebaseId);
await auth.setStatus(adminId,userId,'disabled');await assert.rejects(()=>auth.login('persona@example.com','Nueva2026Clave'),/habilitada/);
console.log('Auth tests passed: Firebase linking, email activation, manual validation, approval, sessions, isolation, reset and disable.');
