import { readFileSync, mkdirSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { DatabaseSync } from 'node:sqlite';
import assert from 'node:assert/strict';
import ts from 'typescript';
const output = resolve('.sites-runtime/tests');
for (const file of ['domain/finance','domain/seed','domain/payment-report','application/ledger-service','infrastructure/d1-ledger']) {
 const source = readFileSync(resolve('src',file+'.ts'),'utf8');
 const js = ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace(/from '(\.\.?\/[^']+)'/g,"from '$1.js'");
 mkdirSync(dirname(resolve(output,file+'.js')),{recursive:true});writeFileSync(resolve(output,file+'.js'),js);
}
const {D1LedgerRepository}=await import(pathToFileURL(resolve(output,'infrastructure/d1-ledger.js')));
const {LedgerService}=await import(pathToFileURL(resolve(output,'application/ledger-service.js')));
const {totals,status}=await import(pathToFileURL(resolve(output,'domain/finance.js')));
const {paymentReport}=await import(pathToFileURL(resolve(output,'domain/payment-report.js')));
const reportObligation={id:'report',month:'2026-09',name:'Reporte',category:'Otros',amount:100,note:'',cutoffDate:null,dueDate:'2026-09-23'};
const reportPayment=(amount,date)=>({id:crypto.randomUUID(),month:'2026-09',kind:'payment',obligationId:'report',amount,date,description:'Prueba'});
assert.equal(paymentReport(reportObligation,[],'2026-09-23').status,'Próximo a vencer');
assert.equal(paymentReport({...reportObligation,dueDate:'2026-09-30'},[],'2026-09-23').status,'Próximo a vencer');
assert.equal(paymentReport({...reportObligation,dueDate:'2026-10-01'},[],'2026-09-23').status,'Pendiente');
assert.equal(paymentReport(reportObligation,[reportPayment(40,'2026-09-22')],'2026-09-24').status,'Vencido');
assert.equal(paymentReport(reportObligation,[reportPayment(40,'2026-09-20'),reportPayment(60,'2026-09-23')],'2026-09-24').status,'Cumplido a tiempo');
assert.equal(paymentReport(reportObligation,[reportPayment(40,'2026-09-20'),reportPayment(60,'2026-09-24')],'2026-09-24').status,'Pagado fuera de plazo');
assert.equal(paymentReport(reportObligation,[reportPayment(100,null)],'2026-09-24').status,'Pago sin fecha');
assert.equal(paymentReport({...reportObligation,dueDate:null},[reportPayment(100,'2026-09-22')],'2026-09-24').status,'Sin fecha límite');
assert.equal(paymentReport({...reportObligation,amount:null},[],'2026-09-24').status,'Sin valor');
assert.equal(paymentReport(reportObligation,[reportPayment(60,'2026-09-23'),reportPayment(40,'2026-09-20')],'2026-09-24').lastDate,'2026-09-23');
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()) sqlite.exec(readFileSync(resolve('drizzle',file),'utf8'));
function prepare(sql,args=[]) { return {bind(...values){return prepare(sql,values)},async first(){return sqlite.prepare(sql).get(...args)??null},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:r.changes},results:[]}},sql,args}; }
const db={prepare,async batch(statements){sqlite.exec('BEGIN');try{const rows=statements.map(s=>{if(/^SELECT/i.test(s.sql.trim()))return {results:sqlite.prepare(s.sql).all(...s.args)};const r=sqlite.prepare(s.sql).run(...s.args);return {results:[],meta:{changes:r.changes}}});sqlite.exec('COMMIT');return rows}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const repo=new D1LedgerRepository(db),service=new LedgerService(repo);
let data=await service.execute({action:'initialize',month:'2026-08'});
assert.equal(data.obligations.length,18);assert.equal(data.movements.length,9);assert.equal(data.obligations.filter(o=>o.amount===null).length,3);assert.equal(data.movements.filter(m=>m.date===null).length,1);
data=await service.execute({action:'initialize',month:'2026-09'});assert.equal(data.movements.length,0);assert.equal(data.obligations.length,18);
const o=data.obligations[0];
assert.equal(o.cutoffDate,null);assert.equal(o.dueDate,null);
data=await service.execute({...o,action:'obligation',cutoffDay:undefined,dueDay:undefined,cutoffDate:'2026-09-25',dueDate:'2026-10-12'});
assert.equal(data.obligations[0].cutoffDate,'2026-09-25');assert.equal(data.obligations[0].dueDate,'2026-10-12');
await assert.rejects(()=>service.execute({...o,action:'obligation',cutoffDate:'2026-02-30',dueDate:null}));
await assert.rejects(()=>service.execute({...o,action:'obligation',cutoffDate:null,dueDate:'2026-13-01'}));
data=await service.execute({...data.obligations[0],action:'obligation',cutoffDay:undefined,dueDay:undefined,cutoffDate:null});assert.equal(data.obligations[0].cutoffDate,null);assert.equal(data.obligations[0].dueDate,'2026-10-12');
const income={action:'movement',month:'2026-09',id:crypto.randomUUID(),kind:'income',obligationId:null,amount:3000000,date:'2026-09-15',description:'Nómina'};
await service.execute(income);await service.execute(income);assert.equal((await repo.read('2026-09')).movements.length,1);
const payment={...income,id:crypto.randomUUID(),kind:'payment',obligationId:o.id,amount:1000000,description:'Abono'};
data=await service.execute(payment);assert.equal(totals(data).available,2000000);assert.equal(status(o,data.movements),'Parcial');
await assert.rejects(()=>service.execute({...payment,id:crypto.randomUUID(),amount:2000000}),/abono supera/);
await assert.rejects(()=>service.execute({...o,action:'obligation',amount:900000}),/valor no puede/);
await assert.rejects(()=>service.execute({...income,id:crypto.randomUUID(),amount:-1}));
await assert.rejects(()=>service.execute({...income,id:crypto.randomUUID(),date:'2026-09-31'}));
await assert.rejects(()=>service.execute({...income,id:crypto.randomUUID(),date:'2026-10-01'}),/fecha debe/);
data=await service.execute({...payment,id:crypto.randomUUID(),amount:o.amount-1000000});assert.equal(status(o,data.movements),'Pagado');
data=await service.execute({action:'removeMovement',month:'2026-09',id:payment.id});assert.equal(status(o,data.movements),'Parcial');
await service.execute({action:'removeMovement',month:'2026-08',id:'import-1'});data=await service.execute({action:'initialize',month:'2026-08'});assert.equal(data.movements.length,8);
data=await service.execute({action:'initialize',month:'2026-10'});assert.equal(data.movements.length,0);assert.equal(data.obligations.length,18);
assert.equal(data.obligations[0].dueDate,'2026-10-12');assert.equal((await repo.read('2026-09')).obligations[0].dueDate,'2026-10-12');
// Reportes derivados del resultado real de cada escritura y reversión.
const reportItem={...reportObligation,id:'integration-report',month:'2026-10',dueDate:'2026-10-15'};
data=await service.execute({...reportItem,action:'obligation'});
const first={action:'movement',id:crypto.randomUUID(),month:'2026-10',kind:'payment',obligationId:reportItem.id,amount:40,date:'2026-10-10',description:'Primer abono'};
const last={...first,id:crypto.randomUUID(),amount:60,date:'2026-10-15',description:'Último abono'};
data=await service.execute(first);data=await service.execute(last);
assert.equal(paymentReport(reportItem,data.movements,'2026-10-16').status,'Cumplido a tiempo');
assert.equal(totals(data).paid,100);
data=await service.execute({action:'removeMovement',month:'2026-10',id:last.id});
let report=paymentReport(reportItem,data.movements,'2026-10-16');
assert.equal(report.status,'Vencido');assert.equal(report.remaining,60);assert.equal(report.lastDate,'2026-10-10');
assert.equal(paymentReport(reportItem,data.movements,'2026-10-14').status,'Próximo a vencer');
assert.equal(totals(data).paid,40);assert.equal(totals(data).available,-40);
data=await service.execute({action:'removeMovement',month:'2026-10',id:first.id});
report=paymentReport(reportItem,data.movements,'2026-10-16');
assert.equal(report.remaining,100);assert.equal(report.lastDate,null);assert.equal(report.hasPayments,false);
assert.equal(totals(data).paid,0);assert.equal(totals(data).available,0);
const correctedIncome={...income,id:crypto.randomUUID(),month:'2026-10',date:'2026-10-15',amount:500};
data=await service.execute(correctedIncome);assert.equal(totals(data).available,500);
const lunch={action:'expense',id:crypto.randomUUID(),month:'2026-10',category:'Restaurante',amount:120,date:'2026-10-15',description:'Almuerzo'};
data=await service.execute(lunch);assert.equal(data.expenses.length,1);assert.equal(totals(data).dailyExpenses,120);assert.equal(totals(data).available,380);
data=await service.execute({...lunch,amount:150,description:'Almuerzo corregido'});assert.equal(data.expenses.length,1);assert.equal(data.expenses[0].description,'Almuerzo corregido');assert.equal(totals(data).available,350);
const voiceExpenses=[{id:crypto.randomUUID(),category:'Gasolina',amount:80000,date:'2026-10-16',description:'Tanqueo'},{id:crypto.randomUUID(),category:'Mercado',amount:120000,date:'2026-10-16',description:'Compra de mercado'}];
data=await service.execute({action:'expenses',month:'2026-10',expenses:voiceExpenses});assert.equal(data.expenses.length,3);assert.equal(totals(data).dailyExpenses,200150);
await assert.rejects(()=>service.execute({action:'expenses',month:'2026-10',expenses:[...voiceExpenses,{...voiceExpenses[0],id:crypto.randomUUID(),date:'2026-11-01'}]}),/fechas deben/);assert.equal((await repo.read('2026-10')).expenses.length,3);
await assert.rejects(()=>service.execute({...lunch,id:crypto.randomUUID(),date:'2026-11-01'}),/fecha debe/);
await assert.rejects(()=>service.execute({...lunch,id:crypto.randomUUID(),category:'Categoría inventada'}));
data=await service.execute({action:'removeExpense',month:'2026-10',id:lunch.id});for(const expense of voiceExpenses)data=await service.execute({action:'removeExpense',month:'2026-10',id:expense.id});assert.equal(data.expenses.length,0);assert.equal(totals(data).dailyExpenses,0);assert.equal(totals(data).available,500);
data=await service.execute({action:'removeMovement',month:'2026-10',id:correctedIncome.id});assert.equal(totals(data).available,0);
assert.equal(paymentReport(reportItem,data.movements,'2026-10-16').status,'Vencido');
assert.deepEqual(totals(await repo.read('2026-10')),totals(data));
console.log('OK: registros, validaciones, reversión y recálculo de reportes, fechas y saldos persistidos.');

// Shared settings propagate to existing future months but preserve prior history.
const recurringId=crypto.randomUUID();
const recurring={action:'obligation',id:recurringId,month:'2026-10',name:'Crédito recurrente',category:'Créditos',amount:500,note:'',cutoffDay:31,dueDay:30,totalDebt:15000,bank:'Banco de prueba',bankingUrl:'https://example.com/banca',interestMV:1.5,interestEA:19.56};
await service.execute(recurring);
await repo.initialize('2027-02');await repo.initialize('2028-02');
const locate=async month=>(await repo.read(month)).obligations.find(o=>o.seriesId===recurringId);
assert.equal((await locate('2027-02')).cutoffDate,'2027-02-28');assert.equal((await locate('2028-02')).dueDate,'2028-02-29');
assert.equal((await locate('2027-02')).totalDebt,15000);assert.equal((await locate('2027-02')).bankingUrl,'https://example.com/banca');
assert.equal((await locate('2027-02')).interestMV,1.5);assert.equal((await locate('2027-02')).interestEA,19.56);
const feb=await locate('2027-02');
await service.execute({...feb,action:'obligation',cutoffDay:15,dueDay:20,totalDebt:13000,interestMV:0,amount:550});
assert.equal((await locate('2028-02')).dueDate,'2028-02-20');assert.equal((await locate('2028-02')).totalDebt,13000);assert.equal((await locate('2028-02')).amount,500);
assert.equal((await locate('2026-10')).cutoffDate,'2026-10-31');assert.equal((await locate('2026-10')).totalDebt,15000);
await service.execute({action:'movement',id:crypto.randomUUID(),month:'2027-02',kind:'payment',obligationId:feb.id,amount:100,date:'2027-02-10',description:'Cuota con intereses'});
assert.equal((await locate('2027-02')).totalDebt,13000);
await assert.rejects(()=>service.execute({...feb,action:'obligation',amount:50,bank:'No guardar'}));assert.equal((await locate('2028-02')).bank,'Banco de prueba');
await service.execute({...await locate('2027-02'),action:'obligation',cutoffDay:null,dueDay:null,totalDebt:null,interestMV:null,interestEA:null,bankingUrl:''});
assert.equal((await locate('2028-02')).dueDate,null);assert.equal((await locate('2028-02')).interestEA,null);
for(const invalid of [{cutoffDay:0},{dueDay:32},{cutoffDay:2.5},{totalDebt:-1},{totalDebt:1.2},{interestMV:-1},{interestEA:-1},{bankingUrl:'javascript:alert(1)'},{bankingUrl:'https://user:password@example.com'}])await assert.rejects(()=>service.execute({...recurring,...invalid}));
console.log('OK: recurrencia, febrero bisiesto, datos de deuda, propagación futura, historia, enlaces seguros y validación.');

// Monthly exception must not leak into newly initialized months.
const amountId=crypto.randomUUID();
const amountItem={...recurring,id:amountId,month:'2028-02',amount:1000};
await service.execute(amountItem);
const amountAt=async month=>(await repo.read(month)).obligations.find(o=>o.seriesId===amountId);
await repo.initialize('2028-03');
await service.execute({...await amountAt('2028-02'),action:'obligation',amount:1200,applyFutureAmount:false});
assert.equal((await amountAt('2028-02')).amount,1200);assert.equal((await amountAt('2028-03')).amount,1000);
await repo.initialize('2028-04');assert.equal((await amountAt('2028-04')).amount,1000);
await service.execute({...await amountAt('2028-04'),action:'obligation',amount:1400});
await repo.initialize('2028-05');assert.equal((await amountAt('2028-05')).amount,1000);
await service.execute({...await amountAt('2028-03'),action:'obligation',amount:1600,applyFutureAmount:true});
assert.equal((await amountAt('2028-02')).amount,1200);
for(const month of ['2028-03','2028-04','2028-05'])assert.equal((await amountAt(month)).amount,1600);
await repo.initialize('2028-06');assert.equal((await amountAt('2028-06')).amount,1600);
const futureItem=await amountAt('2028-06');
const futurePayment={action:'movement',id:crypto.randomUUID(),month:'2028-06',kind:'payment',obligationId:futureItem.id,amount:1500,date:'2028-06-10',description:'Pago de prueba futuro'};
await service.execute(futurePayment);
const beforeAmount=(await amountAt('2028-03')).amount;
const beforeInvalid=await amountAt('2028-03');
await assert.rejects(()=>service.execute({...beforeInvalid,action:'obligation',amount:1300,bank:'No persistir',applyFutureAmount:true}),/valor no puede/);
assert.equal((await amountAt('2028-03')).amount,beforeAmount);assert.equal((await amountAt('2028-06')).bank,'Banco de prueba');
await service.execute({...await amountAt('2028-03'),action:'obligation',amount:1300,applyFutureAmount:false});
assert.equal((await amountAt('2028-06')).amount,1600);assert.equal((await repo.read('2028-06')).movements.find(m=>m.id===futurePayment.id).amount,1500);
console.log('OK: casilla opcional, meses existentes y nuevos, excepciones mensuales, rechazo atómico y pagos intactos.');
